// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhkRy6FXcKmprbuNR88p9cvCCNEAZRoP0',
    appId: '1:760276858085:web:485dda83646abf4c4e500c',
    messagingSenderId: '760276858085',
    projectId: 'ahana-32668',
    authDomain: 'ahana-32668.firebaseapp.com',
    storageBucket: 'ahana-32668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDmWgQiwZ0HqD43QDl5L1Xjxg2G2BciE',
    appId: '1:212066638863:android:27a0e0bb8e9c859c90177a',
    messagingSenderId: '212066638863',
    projectId: 'ahana-ce383',
    storageBucket: 'ahana-ce383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgiUBjTNUBoEtf4gB--80A_r_I01wxZw',
    appId: '1:212066638863:ios:9ad2eb76cf1c0fa390177a',
    messagingSenderId: '212066638863',
    projectId: 'ahana-ce383',
    storageBucket: 'ahana-ce383.firebasestorage.app',
    iosBundleId: 'com.example.ahana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVKkYkl0JtWSBm_PXUep-QQzhysTnzv8',
    appId: '1:760276858085:ios:82ee1e744eae2bf34e500c',
    messagingSenderId: '760276858085',
    projectId: 'ahana-32668',
    storageBucket: 'ahana-32668.firebasestorage.app',
    iosBundleId: 'com.example.ahana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhkRy6FXcKmprbuNR88p9cvCCNEAZRoP0',
    appId: '1:760276858085:web:aeb342544797ef464e500c',
    messagingSenderId: '760276858085',
    projectId: 'ahana-32668',
    authDomain: 'ahana-32668.firebaseapp.com',
    storageBucket: 'ahana-32668.firebasestorage.app',
  );
}